;(lith-define add-trigger (macro (index name params fn) (list 'chaos-add-trigger index name params fn)))
(chaos-add-trigger 1 'acquired '(chaos-flag this acquired text-1))
(chaos-add-trigger 2 'attacked-by '(chaos-script-flag this object))
(chaos-add-trigger #x0D 'exists '(chaos-object-exists object))
(chaos-add-trigger #x0F 'global '(eq? (chaos-get-property text-1) integer-1))
(chaos-add-trigger #x1C 'see '(chaos-can-see this object))
(chaos-add-trigger #x22 'local-timer-expired '(chaos-timer-expired this integer-1))
(chaos-add-trigger #x36 'on-creation '(not (chaos-flag this 'script-executed)))
(chaos-add-trigger #x39 'num-times-talked-to '(= (chaos-get-property this 'num-times-talked-to) integer-1))
(chaos-add-trigger #x39 'num-times-talked-to-gt '(> (chaos-get-property this 'num-times-talked-to) integer-1))
(chaos-add-trigger #x3B 'num-times-talked-to-lt '(< (chaos-get-property this 'num-times-talked-to) integer-1))
(chaos-add-trigger #x51 'dead '(begin (display text-1) (chaos-flag text-1 'dead)))
